#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 29 23:01:02 2025

@author: logan
"""

#Problem 11

dna = "AGTGCAGACGGAGGGCCTACGTGCTTGACATCCCAGTTTTGAGAACAATTTACTATTAACGGATTGGGGCCTATGTAAACAAGTTCCGGCTCGCAAGGCAGTAACGTCTCGCCAGTAGAGTCGATAGAGCCCTGGGTATTCATATGTATTTTTCAGTATAGACTGATAACAACACGCGCGCCTGCGAGGAGAAGAGCACGAGATAAGTCGTAATACCGAAGCTCATAGAGTGTGGTCCATTCTGCGAGGTCGAGTAGGTTCGGCGAATGGGTGTCTGTCGAATGAAGGCTATGGCGAAAGTGGTTTTTTGACCGAGAGATTGCTGATATGAACTGCCGGGGTCGTTGCCCCCGCCGAGAAAGTCCCAAATGAAGTATCATTCGCGCGGTGTGAGCCATTTTACTGTACAGGTAGCGGTAGGAAACTATATGCAGGGTCTGTCCGGGGTGGCATGTCAACACTAAACTTCTCCCTGATCCGCAACCACTCTACTCTCACGCCGGGGATCGCACGCCCTAGTAAACCATAAGGAGTGACCGAGTCTTCCCAGTCCGTAGTAATAAGAGGCCCGCAGCGAGAGAGATTTATGGGTCACCTATCTTTGTAGTAACTAGTGTAATCTATAAATGTAGGGTCATGGTAGCTGCTGCATGACGATGTGGAGTCACCCAGACACGTGATATTTGGCCTTGCGGCGATATCAGTTTGTAACAGATGGGGGGTATGCGCCTCCTTATAGGGGAACGTGAGGAGGTGGCCTCTCGCAGTGGATTTCGGATTCAGCGACCACCGCGCGCTCCTGAGAGTGTCGATCGAAACGGCCCCCCAGTGGTTGCATTACTATGAGTGCTGCTCTAGCCTCTAACATGCAAATACCACCCCTGGAACCGGTCGACACTATGTGGCGGGTTAGGGTTATATGATGTCAAAACGAATCAAGGAG"

reversedna = dna[::-1]
compliment = ""

for i in reversedna:
    if i == "A":
        compliment += "T"
    elif i == "T":
        compliment += "A"
    elif i == "G":
        compliment += "C"
    else:
        compliment += "G"


print(compliment)